// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckConnection() {
  return window['go']['main']['App']['CheckConnection']();
}

export function GetHeight() {
  return window['go']['main']['App']['GetHeight']();
}

export function IsMoving() {
  return window['go']['main']['App']['IsMoving']();
}

export function MoveByStep(arg1) {
  return window['go']['main']['App']['MoveByStep'](arg1);
}

export function MoveToHeight(arg1) {
  return window['go']['main']['App']['MoveToHeight'](arg1);
}
