// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckConnection():Promise<string>;

export function GetHeight():Promise<number>;

export function IsMoving():Promise<boolean>;

export function MoveByStep(arg1:boolean):Promise<void>;

export function MoveToHeight(arg1:number):Promise<void>;
